config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth'

  resources :users, except: :show
  resources :ruby_gems, except: :show

  namespace :api, defaults: { format: :json } do
    post 'query', to: 'gems#query'
  end

  root to: "ruby_gems#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    else
      can :manage, RubyGem, :user_id => user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  validates :name, presence: true
  belongs_to :ruby_gem, optional: true
end

app/models/ruby_gem.rb
class RubyGem < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name

  belongs_to :user
  has_many :libraries, dependent: :destroy

  accepts_nested_attributes_for :libraries, :reject_if => :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/gems_controller.rb
class Api::GemsController < ApplicationController

  def query
    render json: RubyGem.joins(:libraries).where(name: params[:gems].to_a,:libraries => { :os_name => params[:os] }).group('ruby_gems.id').map{
        |gem| {name: gem.name, libraries: gem.libraries.map{ |l| l.name }}
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
  semantic_breadcrumb "Home", :root_path
end

app/controllers/ruby_gems_controller.rb
class RubyGemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_ruby_gem, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  semantic_breadcrumb "Gems", :ruby_gems_path

  def index
    @ruby_gems = RubyGem.all.accessible_by(current_ability)
  end

  def show
  end

  def new
    semantic_breadcrumb "Create", new_ruby_gem_path
    @ruby_gem = RubyGem.new
  end

  def edit
    semantic_breadcrumb @ruby_gem.name
  end

  def create
    @ruby_gem = RubyGem.new(ruby_gem_params)
    @ruby_gem.user = current_user

    if @ruby_gem.save
      redirect_to ruby_gems_url, notice: 'Gem was successfully created.'
    else
      semantic_breadcrumb "Create", new_ruby_gem_path
      render :new
    end
  end

  def update
    if @ruby_gem.update(ruby_gem_params)
      redirect_to ruby_gems_url, notice: 'Gem was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ruby_gem.destroy
    redirect_to ruby_gems_url, notice: 'Gem was successfully destroyed.'
  end

  private
  def set_ruby_gem
    @ruby_gem = RubyGem.find(params[:id])
  end

  def ruby_gem_params
    params.require(:ruby_gem).permit(:name, :version, libraries_attributes: [:id, :name, :os_name, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :is_admin?
  semantic_breadcrumb "Users", :users_path

  def index
    @users = User.all
  end

  def new
    semantic_breadcrumb "Create", new_user_path
    @user = User.new
  end

  def edit
    semantic_breadcrumb @user.email
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      semantic_breadcrumb "Create", new_user_path
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, alert: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name,:email,:password,:is_admin)
    end

    def is_admin?
      unless current_user.is_admin
        redirect_to root_path, alert: 'Access denied.'
      end
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="ui negative message">
      <i class="close icon"></i>
      <div class="header">
        This form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul class="list">
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gems Man</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= controller.controller_name %>">

<div class="ui attached stackable menu">
  <div class="ui container">
    <%= link_to "Gems Man", root_path, {:class => "header item header-logo"} %>

    <% if user_signed_in? %>
        <%= link_to ruby_gems_path, :class => 'item' do %>
            <i class="block layout icon"></i> Gems
        <% end %>

        <% if current_user.try(:is_admin?) %>
            <%= link_to users_path, :class => 'item' do %>
                <i class="users icon"></i> Users
            <% end %>
        <% end %>

        <%= link_to destroy_user_session_path, :class => 'right item', method: :delete, data: {confirm: 'Are you sure?'} do  %>
            <i class="sign out icon"></i> Logout
        <% end %>
    <% else %>
        <div class="right item user-menu-buttons">
          <%= link_to new_user_session_path, :class => 'ui teal button' do  %>
              <i class="sign in icon"></i> Sign In
          <% end %>
          <%= link_to new_user_registration_path, :class => 'ui mini teal button' do  %>
              <i class="users icon"></i> Sign Up
          <% end %>
        </div>
    <% end %>
    </p>

  </div>
</div>

<% if notice %>
    <div class="ui container green inverted segment">
      <p><%= notice %></p>
    </div>
<% end %>

<% if alert %>
    <div class="ui container red inverted segment">
      <p><%= alert %></p>
    </div>
<% end %>

<% if controller.controller_name != "dashboard" %>
    <div class="ui container segment">
      <%= semantic_breadcrumbs %>
    </div>
<% end %>

<div class="ui container segment">
  <%= yield %>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.ui.dropdown').dropdown();
        $('.ui.checkbox').checkbox();
        $('.menu .item').tab();
    });
</script>

</body>
</html>

app/views/ruby_gems/_form.html.erb
<%= form_for(ruby_gem, :html => {:class => "ui large form error"}) do |f| %>

    <%= render 'layouts/error_messages', object: ruby_gem %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :version %>
      <%= f.text_field :version %>
    </div>

    <div class="ui field">
      <%= f.label "system Libraries" %>
      <div id="libraries">
        <%= f.fields_for :libraries do |library| %>
            <%= render 'library_fields', f: library %>
        <% end %>
        <div class="links">
          <%= link_to_add_association  f, :libraries do %>
              <i class="plus icon"></i> Add Library
          <% end %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Save", :class => "ui small blue submit button" %>
    </div>
<% end %>

app/views/ruby_gems/_library_fields.html.erb
<div class="ui segment nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: :name %>
  </div>
  <div class="field">
    <%= f.label "Operating System" %>
    <%= f.select(:os_name, ["ubuntu","centos"].map { |value| [ value.to_s.capitalize, value ] }, placeholder: :os_name) %>
  </div>
  <%= link_to_remove_association f, :class => "ui tiny red icon button" do %>
      <i class="remove icon"></i> Remove
  <% end %>
</div>

app/views/ruby_gems/edit.html.erb
<h1>Editing Gem</h1>

<%= render 'form', ruby_gem: @ruby_gem %>

app/views/ruby_gems/index.html.erb
<h1>
  Gems
  <%= link_to new_ruby_gem_path, class: "ui green small labeled icon add button right" do %>
      <i class="add icon"></i> New Gem
  <% end %>
</h1>

<table class="ui table">
  <thead>
  <tr>
    <th>Name</th>
    <th>By</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% if @ruby_gems.each do |ruby_gem| %>
      <tr>
        <td><%= ruby_gem.name %></td>
        <td><%= ruby_gem.user.email %></td>
        <td class="right aligned">
          <div class="ui buttons mini">
            <%= link_to edit_ruby_gem_path(ruby_gem), class: "ui button" do %>
                <i class="edit icon"></i> Edit
            <% end %>
            <%= link_to ruby_gem_path(ruby_gem), method: :delete, data: {confirm: 'Are you sure?'}, class: "ui button" do %>
                <i class="trash icon"></i> Delete
            <% end %>
          </div>
        </td>
      </tr>
  <% end.empty? %>
  <tr>
    <td colspan="2">
      <strong>Nothing to show right now!!</strong>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/ruby_gems/new.html.erb
<h1>New Gem</h1>

<%= render 'form', ruby_gem: @ruby_gem %>

app/views/ruby_gems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ruby_gem.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @ruby_gem.version %>
</p>

<p>
  <strong>User:</strong>
  <%= @ruby_gem.user %>
</p>

<%= link_to 'Edit', edit_ruby_gem_path(@ruby_gem) %> |
<%= link_to 'Back', ruby_gems_path %>

app/views/users/_form.html.erb
<%= form_for(user, :html => {:class => "ui large form error"}) do |f| %>

    <%= render 'layouts/error_messages', object: user %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="inline field">
      <div class="ui toggle checkbox">
        <%= f.check_box(:is_admin) %>
        <%= f.label(:is_admin, "Admin?") %>
      </div>
    </div>

    <%= f.submit :class => "ui small blue submit button" %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>
  Users
  <%= link_to new_user_path, class: "ui green small labeled icon add button right" do %>
      <i class="add icon"></i> New User
  <% end %>
</h1>

<table class="ui table">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% if @users.each do |user| %>
      <tr>
        <td><strong><%= user.email %></strong></td>
        <td class="right aligned">
          <div class="ui buttons mini">
            <%= link_to edit_user_path(user), class: "ui button" do %>
                <i class="edit icon"></i> Edit
            <% end %>
            <%= link_to user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: "ui button" do %>
                <i class="trash icon"></i> Delete
            <% end %>
          </div>
        </td>
      </tr>
  <% end.empty? %>
      <tr>
        <td colspan="2">
          <strong>Nothing to show right now!!</strong>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>